### ISSUE TITLE
Changeset Actions

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#794]
Ideas for possible new changeset actions:
- [ ] `extendFeedSchedule` (related to #647)
- [x] `changeOnestopId` (will be implemented on #332)
- [x] `mergeOnestopIds` (will be implemented on #332)

**Comment by drewda** [comment]
change and merge actions for Onestop IDs have been added in https://github.com/transitland/transitland-datastore/issues/910

Being able to extend feed schedules from outside hasn't been necessary, so closing this.
